config/routes.rb
Blippity::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :question_answers

  resources :levels do 
    resources :question_answers
  end

  
  match '/play',       :to => 'games#play'
  match '/play/blips', :to => 'games#blips'
  match '/play/blops', :to => 'games#blops'
  match '/play/cocos', :to => 'games#cocos'
  match '/play/ghost', :to => 'games#ghost'

  match '/about', :to => 'pages#about'
  root :to => 'pages#index'
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :question_answers
  attr_accessible :level, :title
  
end

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base
  belongs_to :level
  
  validates_presence_of :answer
  validates_presence_of :question
  validates_uniqueness_of :question
  validates_numericality_of :bonus, :only_integer => true, :greater_than_or_equal_to => 0
  validates_numericality_of :score, :only_integer => true, :greater_than_or_equal_to => 0
  
  attr_accessible :answer, :bonus, :level, :question, :score
  
  before_create :generate_bonus
  before_create :generate_score
  
  def generate_bonus
    self.bonus = self.answer.length * 10
  end

  def generate_score
    self.score = self.level.level * 10
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]
  attr_accessible :provider, :uid

  attr_accessible :username, :name, :image_url

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def display_name
    username || email.gsub(/\@.*$/,'@')
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(
         provider:auth.provider,
         uid:auth.uid,
         email:auth.info.email,
         name:auth.info.name,
         username:auth.info.username,
         image_url:auth.info.image,
         password:Devise.friendly_token[0,20]
      )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  before_filter :authenticate_user!
  
  def play
    @title = "play"
    @levels = Level.order('level asc')
  end
  
  def blips
    @title = "blips"
    @levels = Level.order('level asc')
  end
    
  def blops
    @title = "blops"
    @levels = Level.order('level asc')
  end

  def cocos
    @title = "cocos"
  end

  def ghost
    @title = "ghost"
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @levels }
    end
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
    @level = Level.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @level }
    end
  end

  # GET /levels/new
  # GET /levels/new.json
  def new
    @level = Level.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @level }
    end
  end

  # GET /levels/1/edit
  def edit
    @level = Level.find(params[:id])
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(params[:level])

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render json: @level, status: :created, location: @level }
      else
        format.html { render action: "new" }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /levels/1
  # PUT /levels/1.json
  def update
    @level = Level.find(params[:id])

    respond_to do |format|
      if @level.update_attributes(params[:level])
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level = Level.find(params[:id])
    @level.destroy

    respond_to do |format|
      format.html { redirect_to levels_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @title = "welcome"
  end

  def about
    @title = "about"
  end
  
end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_level
    
  # GET /question_answers
  # GET /question_answers.json
  def index
    @question_answers = @level.question_answers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_answers }
    end
  end

  # GET /question_answers/1
  # GET /question_answers/1.json
  def show
    @question_answer = QuestionAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_answer }
    end
  end

  # GET /question_answers/new
  # GET /question_answers/new.json
  def new
    @question_answer = QuestionAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_answer }
    end
  end

  # GET /question_answers/1/edit
  def edit
    @question_answer = QuestionAnswer.find(params[:id])
  end

  # POST /question_answers
  # POST /question_answers.json
  def create
    @question_answer = QuestionAnswer.new(params[:question_answer])

    respond_to do |format|
      if @question_answer.save
        format.html { redirect_to level_question_answer_path(@level, @question_answer), notice: 'Question answer was successfully created.' }
        format.json { render json: @question_answer, status: :created, location: @question_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_answers/1
  # PUT /question_answers/1.json
  def update
    @question_answer = QuestionAnswer.find(params[:id])

    respond_to do |format|
      if @question_answer.update_attributes(params[:question_answer])
        format.html { redirect_to level_question_answer_path(@level, @question_answer), notice: 'Question answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_answers/1
  # DELETE /question_answers/1.json
  def destroy
    @question_answer = QuestionAnswer.find(params[:id])
    @question_answer.destroy

    respond_to do |format|
      format.html { redirect_to level_question_answers_url(@level) }
      format.json { head :no_content }
    end
  end
  
  private 
  
  def load_level
    @level = Level.find(params[:level_id])
  end
    
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/views/games/blips.haml
%h3
  coming soon

%p
  excited?  i am.
%p
  you should be, too.

app/views/games/blops.haml
:javascript
  var blopManager;
  $(document).ready( function() {
    var maxNumberOfBlipsAtATime = jQuery.browser.mobile ? 20 : 40;
    var domNodeParent    = '#wrap';
    blopManager = new BlipManager(maxNumberOfBlipsAtATime, domNodeParent);
    $('#gamePlayPause').bind('click', function(){
      blopManager.toggle();
    });
    $('body').keyup(function(e){
      if(e.keyCode == 72 || e.keyCode == 104 || e.keyCode == 63 || e.keyCode == 191){
        $('#helpModal').modal('toggle');
      }
    });    
  });
#scoreboard
  .points
    %b
      score
    %span#score
    %b
      wrong
    %span#wrong
    %b
      right
    %span#right
    .hide
      %b
        pairs
      %span#total
      %b
        bonus
      %span#bonus
      
#dash.pull-right
  #controls
    %span#erase
      %i.icon-remove-sign
      try again
    %span#next
      %i.icon-circle-arrow-right
      next
  #miscellaneous
    %span#help{ :href => '#helpModal', :role => :button, :data => { :toggle => :modal} }
      %i.icon-question-sign
      help

      
#blops.hide
  #question
  #answer
  #status
    &nbsp;

#levels.hide
  %h2 Levels
  -@levels.each do |level|
    .level{:data => { :level => "#{level.level}" } }
      .number{:data => { :level => "#{level.level}" } }
        =level.level
      .title
        =level.title

#helpModal.modal.hide.fade{ :tabindex => -1, :role => :dialog, :aria => { :labelledBy => :helpModelLabel, :hidden => :true} }
  .modal-header
    %button.close{ :data => { :dismiss => :modal }, :aria => { :hidden => true } }
      %i.icon-remove
    %h3#myModalHelp
      blop help
  .modal-body

    %h4
      goal
    %p
      i will give you a word.
    %p
      you figure out the other word.
    %p
      i will always give you a hint, one letter at a time.  as you get better, i get more recalcitrant, as it were.

    %h4
      %i.icon-play-sign 
      play,
      %i.icon-pause
      pause
    %p
      %b
        click 
      on them at the top of the window to start and stop our game whenever you like.
    %p
      or press
      %b
        spacebar

    %h4
      %i.icon-remove-sign
      try again
    %p
      make a mistake?
      
    %h4
      %i.icon-circle-arrow-right
      next  
    %p
      give up?  of course you won't ... but if you do.
    %p
      or press your keyboard's 
      %b
        right arrow
        
    %h4
      %i.icon-question-sign
      help
    %p
      press
      %b
        h
      or
      %b
        ?
      to open and close this help screen.
    %p
      it is sort of a self-referencing kind of thing.  i like being canonical.  you?
              
  .modal-footer
    %button.btn{ :data => { :dismiss => :modal }, :aria => { :hidden => :true } }
      close

app/views/games/cocos.haml
.cocos{ :style => "display:inline-block;width:auto; margin: 0 auto; background: black; border:5px solid black; border-radius: 10px; box-shadow: 0 5px 50px #333"}
  %canvas#gameCanvas{ :width => 800,  :height => 450 }
  

%script{ :src => '/cocos/cocos.js',  :type => 'text/javascript' }

app/views/games/ghost.haml
%h1
  ghost
%p
  %a{ :href => 'http://www.raywenderlich.com/32970/how-to-make-a-cross-platform-game-with-cocos2d-javascript-tutorial-getting-started'}
    reference

%p

  .ghost{ :style => "display:inline-block;width:auto; margin: 0 auto; background: white; border:5px solid black; border-radius: 5px; box-shadow: 0 5px 50px #333"}
    %canvas#gameCanvas{ :width => 800,  :height => 450 }  

%script{ :src => '/ghost/ghost.js',  :type => 'text/javascript' }

app/views/games/play.haml
#games
  .game
    %a{ :href => play_blips_path }
      %h1 blips
    %p
      coming soon.
  .game
    %a{ :href => play_blops_path }
      %h1 blops
    %p
      like blops?  me, too.
  .game
    %a{ :href => play_cocos_path }
      %h1 cocos
    %p
      coo coo for cocos? yep.
  .game
    %a{ :href => play_ghost_path }
      %h1 ghost
    %p
      ghost recon.  nah.  ghost busters?  maybe.
  

app/views/layouts/_footer.haml
#footer
  .container
    %p.muted.credit
      all rights reserved.

app/views/layouts/_head.haml
%meta{:content => 'text/xhtml;charset=utf-8', 'http-equiv' => 'content-type'}
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}

%meta{:content => content_for?(:description) ? yield(:description) : "SeattleAstro", :name => "description"}
%meta{:property => 'og:title', :content => 'Blippity'}
%meta{:property => 'og:type', :content => 'website'}
%meta{:property => 'og:url', :content => 'http://blippity.me'}
%meta{:property => 'og:image', :content => 'http://blippity.me/assets/logo.jpg'}
%meta{:property => 'og:description', :content => 'Blippity is a Blip Blub inspired game'}
%meta{:property => 'og:site_name', :content => 'Blippity'}

%link{:rel => 'shortcut icon', :href => '/assets/favicon.ico' }

<!-- generate new icons using http://www.quirco.com/iPhoneIcon -->
%link{ :rel => "apple-touch-icon", :href => "/assets/iPhoneIcon_Small.png" }
%link{ :rel => "apple-touch-icon", :sizes => '72x72',   :href => "/assets/iPhoneIcon_Medium.png" }
%link{ :rel => "apple-touch-icon", :sizes => '114x114', :href => "/assets/iPhoneIcon_Big.png" }
%meta{ :name => 'apple-touch-fullscreen', :content => 'yes'}
%meta{ :name => 'apple-mobile-web-app-capable', :content => 'yes'}

<!-- iPhone SPLASHSCREEN-->
<link href="/assets/apple-touch-startup-image-320x460.png" media="(device-width: 320px)" rel="apple-touch-startup-image">
<!-- iPhone (Retina) SPLASHSCREEN-->
<link href="/assets/apple-touch-startup-image-640x920.png" media="(device-width: 640px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image">

= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"

app/views/layouts/_header.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %button.btn.btn-navbar{ :type => :button, :data => { :toggle => :collapse, :target => ".nav-collapse" } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => root_path}
        blippity
      -if(current_user && params[:controller] == 'games' && ('blops').include?(params[:action]))
        .nav
          %ul.nav
            %li
              %b.small
                lvl
                %level#level
            %li
              %a{:id => 'gamePlayPause'}
                %i.icon-pause
      .nav-collapse.collapse
        %ul.nav
          %li{:class => (params[:controller] == 'pages' && params[:action] == 'index' ? 'active' : nil)}
            %a{:href => root_path}
              welcome
          %li{:class => (params[:controller] == 'pages' && params[:action] == 'about' ? 'active' : nil)}
            %a{:href => about_path}
              about
          -if current_user
            %li{:class => (params[:controller] == 'games' ? 'active' : nil)}
              %a{:href => play_path}
                play

            %li
              -#%a{ :href => edit_user_registration_path(current_user) }
                =current_user.display_name
                -image_tag current_user.image_url
            %li
              %a{ :href => destroy_user_session_path, :data => { :method => :delete} }
                %i.icon-signout
          -else
            %li
              %a{:href => user_omniauth_authorize_path(:facebook)}
                %i.icon-facebook-sign

app/views/layouts/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title= "blippity #{@title ? ('| ' + @title): ''}"
    = render :partial => 'layouts/head'
    = csrf_meta_tags
    = yield(:head)
  %body
    #wrap
      =render :partial => 'layouts/header'
      .container.content{ :id => "#{params[:controller].underscore.gsub(/\//,'_')}"}
        =render :partial => 'layouts/messages'
        = yield
    =render :partial => 'layouts/footer'

app/views/levels/_form.html.haml
= form_for @level do |f|
  - if @level.errors.any?
    #error_explanation
      %h2= "#{pluralize(@level.errors.count, "error")} prohibited this level from being saved:"
      %ul
        - @level.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :points_per_letter_right,
    = f.number_field :points_per_letter_right, :min => 0
  .field
    = f.label :points_per_word_right,
    = f.number_field :points_per_word_right, :min => 0
  .field
    = f.label :points_per_letter_wrong,
    = f.number_field :points_per_letter_wrong, :max => 0
  .field
    = f.label :points_per_word_wrong,
    = f.number_field :points_per_word_wrong, :max => 0
  .field
    = f.label :points_per_clear,
    = f.number_field :points_per_clear, :max => 0
  .actions
    = f.submit 'Save'

app/views/levels/edit.html.haml
%h1 Editing level

= render 'form'

= link_to 'Show', @level
\|
= link_to 'Back', levels_path

app/views/levels/index.html.haml
%h1 Levels

%table
  %tr
    %th Level
    %th Title
    %th
    %th
    %th

  - @levels.each do |level|
    %tr
      %td= level.level
      %td= level.title
      %td= link_to 'Show', level_question_answers_path([level])
      %td= link_to 'Edit', edit_level_path(level)
      %td= link_to 'Destroy', level, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Level', new_level_path

app/views/levels/new.html.haml
%h1 New level

= render 'form'

= link_to 'Back', levels_path

app/views/levels/show.html.haml
%p#notice= notice

%p
  %b Level:
  = @level.level
%p
  %b Title:
  = @level.title

= link_to 'Edit', edit_level_path(@level)
\|
= link_to 'Back', levels_path

app/views/pages/about.haml
%h4
  a poem
%p
  i am about 
  %a{ :href => play_blips_path }
    blips.  
%p
  and
  %a{ :href => play_blops_path }
    blops.  
%p
  and those kind of things.  
%p
  i think.
%p
  maybe.
%p
  most likely.

%p
  &nbsp;
  
%h4
  a speech
%p
  the 
  %a{ :href => 'http://wardspics.com' }
    man behind me 
  is really more into 
  %a{ :href => 'http://github.com/wwvuillemot/blippity' }
    tech-demos, 
  whatever those are.
%p
  he promises me that eventually he will take me more seriously than just a hobby.
%p
  sort of like steve j. et al. and that fruit tv thing they have going on down in cali.
%p
  but in the meantime, you might just find in me a 
  %a{ :href => play_path}
    few games, 
  as it were.

app/views/pages/index.haml
-if current_user
  %p
    hi, 
    %b
      #{current_user.display_name}.
  %p
    wanna
    %a{ :href => play_path }
      play?
-else
  %p
    hi. i'm blippity.
  %p
    and
    %a{:href => user_omniauth_authorize_path(:facebook)}
      you?

app/views/question_answers/_form.html.haml
= form_for([@level, @question_answer]) do |f|
  - if @question_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question_answer.errors.count, "error")} prohibited this question_answer from being saved:"
      %ul
        - @question_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :question
    = f.text_field :question
  .field
    = f.label :answer
    = f.text_field :answer
  .field
    = f.label :score
    = f.number_field :score, :min => 0
  .field
    = f.label :bonus
    = f.number_field :bonus, :min => 0
  .actions
    = f.submit 'Save'

app/views/question_answers/edit.html.haml
%h1 Editing question_answer

= render 'form'

= link_to 'Show', level_question_answer_path(@level, @question_answer)
\|
= link_to 'Back', level_question_answers_path(@level)

app/views/question_answers/index.html.haml
%h1 Level #{@level.level} Q &amp; A's

%table
  %tr
    %th Q
    %th A
    %th Score
    %th Bonus
    %th
    %th
    %th

  - @question_answers.each do |question_answer|
    %tr
      %td= question_answer.question
      %td= question_answer.answer
      %td= question_answer.score
      %td= question_answer.bonus
      %td= link_to 'Show', level_question_answer_path(@level, question_answer)
      %td= link_to 'Edit', edit_level_question_answer_path(@level, question_answer)
      %td= link_to 'Destroy', question_answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Q & A', new_level_question_answer_path(@level)

app/views/question_answers/new.html.haml
%h1 New question_answer

= render 'form'

= link_to 'Back', question_answers_path

app/views/question_answers/show.html.haml
%p#notice= notice

%p
  %b Question:
  = @question_answer.question
%p
  %b Answer:
  = @question_answer.answer
%p
  %b Score:
  = @question_answer.score
%p
  %b Bonus:
  = @question_answer.bonus

= link_to 'Edit', edit_level_question_answer_path(@level, @question_answer)
\|
= link_to 'Back', level_question_answers_path(@level)